#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : libxfce4ui
Version  : 4.18.4
Release  : 36
URL      : https://archive.xfce.org/src/xfce/libxfce4ui/4.18/libxfce4ui-4.18.4.tar.bz2
Source0  : https://archive.xfce.org/src/xfce/libxfce4ui/4.18/libxfce4ui-4.18.4.tar.bz2
Summary  : Private Xfce library for shared code between xfwm4 and xfce4-settings
Group    : Development/Tools
License  : LGPL-2.0
Requires: libxfce4ui-bin = %{version}-%{release}
Requires: libxfce4ui-data = %{version}-%{release}
Requires: libxfce4ui-lib = %{version}-%{release}
Requires: libxfce4ui-license = %{version}-%{release}
Requires: libxfce4ui-locales = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : docbook-xml
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : gtk3-dev
BuildRequires : intltool
BuildRequires : libxslt-bin
BuildRequires : perl
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : pkgconfig(libxfconf-0)
BuildRequires : pkgconfig(sm)
BuildRequires : startup-notification-dev
BuildRequires : vala
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Set-default-keyboard-shortcuts-for-use-within-Clear-.patch

%description
[![License](https://img.shields.io/badge/License-GPL%20v2-blue.svg)](https://gitlab.xfce.org/xfce/libxfce4ui/-/blob/master/COPYING)

%package bin
Summary: bin components for the libxfce4ui package.
Group: Binaries
Requires: libxfce4ui-data = %{version}-%{release}
Requires: libxfce4ui-license = %{version}-%{release}

%description bin
bin components for the libxfce4ui package.


%package data
Summary: data components for the libxfce4ui package.
Group: Data

%description data
data components for the libxfce4ui package.


%package dev
Summary: dev components for the libxfce4ui package.
Group: Development
Requires: libxfce4ui-lib = %{version}-%{release}
Requires: libxfce4ui-bin = %{version}-%{release}
Requires: libxfce4ui-data = %{version}-%{release}
Provides: libxfce4ui-devel = %{version}-%{release}
Requires: libxfce4ui = %{version}-%{release}

%description dev
dev components for the libxfce4ui package.


%package doc
Summary: doc components for the libxfce4ui package.
Group: Documentation

%description doc
doc components for the libxfce4ui package.


%package lib
Summary: lib components for the libxfce4ui package.
Group: Libraries
Requires: libxfce4ui-data = %{version}-%{release}
Requires: libxfce4ui-license = %{version}-%{release}

%description lib
lib components for the libxfce4ui package.


%package license
Summary: license components for the libxfce4ui package.
Group: Default

%description license
license components for the libxfce4ui package.


%package locales
Summary: locales components for the libxfce4ui package.
Group: Default

%description locales
locales components for the libxfce4ui package.


%prep
%setup -q -n libxfce4ui-4.18.4
cd %{_builddir}/libxfce4ui-4.18.4
%patch1 -p1
pushd ..
cp -a libxfce4ui-4.18.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1685632857
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffunction-sections -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffunction-sections -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffunction-sections -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffunction-sections -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static --with-vendor-info="Clear Linux Project for Intel Architecture" \
--disable-introspection
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static --with-vendor-info="Clear Linux Project for Intel Architecture" \
--disable-introspection
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1685632857
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libxfce4ui
cp %{_builddir}/libxfce4ui-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libxfce4ui/3cc956929ff9e4c1c89a2c826cdc7fec5e0b21ab || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
%find_lang libxfce4ui
## install_append content
mv %{buildroot}%{_sysconfdir}/xdg %{buildroot}%{_datadir}/. && rmdir %{buildroot}%{_sysconfdir} && install -d -D -m 00755 %{buildroot}%{_datadir}/xfce4 && echo "Clear Linux Project for Intel Architecture" > %{buildroot}%{_datadir}/xfce4/vendorinfo
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/xfce4-about
/usr/bin/xfce4-about

%files data
%defattr(-,root,root,-)
/usr/share/applications/xfce4-about.desktop
/usr/share/icons/hicolor/128x128/apps/org.xfce.about.png
/usr/share/icons/hicolor/128x128/apps/xfce4-logo.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.about.png
/usr/share/icons/hicolor/16x16/apps/xfce4-logo.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.about.png
/usr/share/icons/hicolor/48x48/apps/xfce4-logo.png
/usr/share/icons/hicolor/scalable/apps/org.xfce.about.svg
/usr/share/icons/hicolor/scalable/apps/xfce4-logo.svg
/usr/share/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
/usr/share/xfce4/vendorinfo

%files dev
%defattr(-,root,root,-)
/usr/include/xfce4/libxfce4kbd-private-3/libxfce4kbd-private/xfce-shortcut-dialog.h
/usr/include/xfce4/libxfce4kbd-private-3/libxfce4kbd-private/xfce-shortcuts-editor-dialog.h
/usr/include/xfce4/libxfce4kbd-private-3/libxfce4kbd-private/xfce-shortcuts-editor.h
/usr/include/xfce4/libxfce4kbd-private-3/libxfce4kbd-private/xfce-shortcuts-grabber.h
/usr/include/xfce4/libxfce4kbd-private-3/libxfce4kbd-private/xfce-shortcuts-provider.h
/usr/include/xfce4/libxfce4kbd-private-3/libxfce4kbd-private/xfce-shortcuts-xfwm4.h
/usr/include/xfce4/libxfce4kbd-private-3/libxfce4kbd-private/xfce-shortcuts.h
/usr/include/xfce4/libxfce4ui-2/libxfce4ui/libxfce4ui-config.h
/usr/include/xfce4/libxfce4ui-2/libxfce4ui/libxfce4ui-enum-types.h
/usr/include/xfce4/libxfce4ui-2/libxfce4ui/libxfce4ui.h
/usr/include/xfce4/libxfce4ui-2/libxfce4ui/xfce-dialogs.h
/usr/include/xfce4/libxfce4ui-2/libxfce4ui/xfce-filename-input.h
/usr/include/xfce4/libxfce4ui-2/libxfce4ui/xfce-gdk-extensions.h
/usr/include/xfce4/libxfce4ui-2/libxfce4ui/xfce-gtk-extensions.h
/usr/include/xfce4/libxfce4ui-2/libxfce4ui/xfce-screensaver.h
/usr/include/xfce4/libxfce4ui-2/libxfce4ui/xfce-sm-client.h
/usr/include/xfce4/libxfce4ui-2/libxfce4ui/xfce-spawn.h
/usr/include/xfce4/libxfce4ui-2/libxfce4ui/xfce-titled-dialog.h
/usr/lib64/libxfce4kbd-private-3.so
/usr/lib64/libxfce4ui-2.so
/usr/lib64/pkgconfig/libxfce4kbd-private-3.pc
/usr/lib64/pkgconfig/libxfce4ui-2.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/libxfce4ui/XfceFilenameInput.html
/usr/share/gtk-doc/html/libxfce4ui/XfceSMClient.html
/usr/share/gtk-doc/html/libxfce4ui/XfceScreensaver.html
/usr/share/gtk-doc/html/libxfce4ui/XfceTitledDialog.html
/usr/share/gtk-doc/html/libxfce4ui/annotation-glossary.html
/usr/share/gtk-doc/html/libxfce4ui/api-index-4-10.html
/usr/share/gtk-doc/html/libxfce4ui/api-index-4-12.html
/usr/share/gtk-doc/html/libxfce4ui/api-index-4-14.html
/usr/share/gtk-doc/html/libxfce4ui/api-index-4-16.html
/usr/share/gtk-doc/html/libxfce4ui/api-index-4-18.html
/usr/share/gtk-doc/html/libxfce4ui/api-index-deprecated.html
/usr/share/gtk-doc/html/libxfce4ui/api-index-full.html
/usr/share/gtk-doc/html/libxfce4ui/home.png
/usr/share/gtk-doc/html/libxfce4ui/index.html
/usr/share/gtk-doc/html/libxfce4ui/left-insensitive.png
/usr/share/gtk-doc/html/libxfce4ui/left.png
/usr/share/gtk-doc/html/libxfce4ui/libxfce4ui-Gdk-Extensions.html
/usr/share/gtk-doc/html/libxfce4ui/libxfce4ui-Gtk-Extensions.html
/usr/share/gtk-doc/html/libxfce4ui/libxfce4ui-Spawn.html
/usr/share/gtk-doc/html/libxfce4ui/libxfce4ui-XfceDialogs.html
/usr/share/gtk-doc/html/libxfce4ui/libxfce4ui-extensions.html
/usr/share/gtk-doc/html/libxfce4ui/libxfce4ui-fundamentals.html
/usr/share/gtk-doc/html/libxfce4ui/libxfce4ui-introduction.html
/usr/share/gtk-doc/html/libxfce4ui/libxfce4ui-libxfce4ui-config.html
/usr/share/gtk-doc/html/libxfce4ui/libxfce4ui-sm.html
/usr/share/gtk-doc/html/libxfce4ui/libxfce4ui-widgets.html
/usr/share/gtk-doc/html/libxfce4ui/libxfce4ui.devhelp2
/usr/share/gtk-doc/html/libxfce4ui/right-insensitive.png
/usr/share/gtk-doc/html/libxfce4ui/right.png
/usr/share/gtk-doc/html/libxfce4ui/style.css
/usr/share/gtk-doc/html/libxfce4ui/up-insensitive.png
/usr/share/gtk-doc/html/libxfce4ui/up.png

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libxfce4kbd-private-3.so.0.0.0
/V3/usr/lib64/libxfce4ui-2.so.0.0.0
/usr/lib64/libxfce4kbd-private-3.so.0
/usr/lib64/libxfce4kbd-private-3.so.0.0.0
/usr/lib64/libxfce4ui-2.so.0
/usr/lib64/libxfce4ui-2.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libxfce4ui/3cc956929ff9e4c1c89a2c826cdc7fec5e0b21ab

%files locales -f libxfce4ui.lang
%defattr(-,root,root,-)

